#APPLICATION FORM
name=input("Enter your name : ")
gender=input("Enter your gender : ")
state=input("Enter your state : ")
DOB=input("Enter you date of birth : ")
community=input("Enter your community : ")
whatsapp_num=int(input("Enter your whatsapp number : "))
email_id=input("Enter your E mail id : ")
mark_10th=int(input("Enter your 10th mark : "))
mark_12th=int(input("Enter your 12th mark : "))
father_name=input("Enter your father's name : ")
father_occupation=input("Enter your father's occupation : ")
father_mobile_num=int(input("Enter your father's mobile number : "))
mother_name=input("Enter your mother's name : ")
mother_occupation=input("Enter your mother's occupation : ")
mother_mobile_num=int(input("Enter your mother's mobile number : "))
school_name=input("Enter your school name : ")
board=input("Enter your board of studied : ")
medium=input("Enter your medium of studied : ")
school_address=input("Enter your school address with pin code : ")
house_address=input("Enter your house address with pin code : ")
course_1=input("Enter youe first preference of course : ")
course_2=input("Enter youe second preference of course : ")
course_3=input("Enter youe third preference of course : ")
print("\nAPPLICATION FORM")
print("===============")
print("\n\nBASIC DETAILS ==>\n\n")
print("\tSTUDENT NAME : ",name)
print("\tGENDER : ",gender)
print("\tSTATE : ",state)
print("\tDATE OF BIRTH : ",DOB)
print("\tCOMMUNITY : ",community)
print("\tWHATSAPP NUMBER : ",whatsapp_num)
print("\tE-MAIL ID : ",email_id)
print("\n\nMARKS==>\n\n")
print("\t10thMARK : ",mark_10th)
print("\t12thMARK : ",mark_12th)
print("\n\nFATHER's DETAILS==>\n\n")
print("\tFATHER's NAME : ",father_name)
print("\tFATHER's OCCUPATION : ",father_occupation)
print("\tFATHER's MOBILE NUMBER : ",father_mobile_num)
print("\n\nMOTHER's DETAILS==>\n\n")
print("\tMOTHER's NAME : ",mother_name)
print("\tMOTHER's OCCUPATION : ",mother_occupation)
print("\tMOTHER's MOBILE NUMBER : ",mother_mobile_num)
print("\n\nSCHOOL DETAILS==>\n\n")
print("\tSCHOOL NAME : ",school_name)
print("\tBOARD : ",board)
print("\tMEDIUM : ",medium)
print("\tADDRESS : ",school_address)
print("\n\nHOME ADDRESS==>\n\n")
print("\t",house_address)
print("\n\nCOURSE PREFERENCE==>\n\n")
print("\tOPTION 1 : ",course_1)
print("\tOPTION 2 : ",course_2)
print("\tOPTION 3 : ",course_3)

