#DATE TIME IN PYTHON
import datetime as dt
current_date=dt.date.today()
print("CURRENT DATE : ",current_date)
d=dt.date(2005,3,7)
print("YEAR : ",d.year)
print("MONTH : ",d.month)
print("DAY : ",d.day)
current_time=dt.datetime.now()
print("CURRENT DATE AND TIME : ",current_time)
t=dt.time(11,55,45,55500)
print("HOURS : ",t.hour)
print("MINUTES : ",t.minute)
print("SECONDS : ",t.second)
print("MICROSECONDS : ",t.microsecond)
new=dt.datetime(2005,3,7,8,59,58)
print("FULL DATE AND TIME : ",new)
print("DATE : ",new.date())
print("TIME : ",new.time())
current=dt.datetime.now()
my=int(input("Enter the next newyear : "))
newyear=dt.datetime(my,1,1)
dif=newyear-current
print("DIFFERENCE FROM NOW TO COMING NEWYEAR : ",dif)
fin=dt.datetime.now()
print("FULL DETAILS : ",fin)
s=fin.strftime("%A %B %d %y")
print("ALL DETAILS : ",s)
